version: '2'
services:
  web:
    build: .
    ports:
      - "3080:3080"
      - "3443:3443"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
    environment:
      - TOOMEAN_MONGO_HOST=mongo
    command: >
      sh -c '
      if test -d node_modules;
      then
        echo node_modules_exists;
      else
        cp -a /tmp/node_modules /usr/src/app;
      fi &&
      npm install &&
      npm start
      '
  mongo:
    image: "mongo"
