version: '2'
services:
  web:
    build: .
    ports:
      - "3080:3080"
      - "3443:3443"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
    environment:
      - TOOMEAN_MONGO_HOST=mongo
  mongo:
    image: "mongo"
